name: TimeSeries
channels:
  - defaults
dependencies:
  - python=3.8 
  - jupyter=1.0.0
  - numpy=1.20.3
  - pip=21.1.3
  - pip:
    - ruptures==1.1.4
    - scipy==1.7.0
    - tqdm==4.61.2
    - pandas==1.3.0
    - matplotlib==3.4.2
    - repackage==0.7.3